// Autogenerated from Pigeon (v21.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "platform_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace vpn_plugin {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// Server

Server::Server(
  int64_t id,
  const std::string& name,
  const std::string& ip_address,
  const std::string& domain,
  const std::string& login,
  const std::string& password,
  const VpnProtocol& protocol,
  int64_t routing_profile_id,
  const EncodableList& dns_servers)
 : id_(id),
    name_(name),
    ip_address_(ip_address),
    domain_(domain),
    login_(login),
    password_(password),
    protocol_(protocol),
    routing_profile_id_(routing_profile_id),
    dns_servers_(dns_servers) {}

int64_t Server::id() const {
  return id_;
}

void Server::set_id(int64_t value_arg) {
  id_ = value_arg;
}


const std::string& Server::name() const {
  return name_;
}

void Server::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& Server::ip_address() const {
  return ip_address_;
}

void Server::set_ip_address(std::string_view value_arg) {
  ip_address_ = value_arg;
}


const std::string& Server::domain() const {
  return domain_;
}

void Server::set_domain(std::string_view value_arg) {
  domain_ = value_arg;
}


const std::string& Server::login() const {
  return login_;
}

void Server::set_login(std::string_view value_arg) {
  login_ = value_arg;
}


const std::string& Server::password() const {
  return password_;
}

void Server::set_password(std::string_view value_arg) {
  password_ = value_arg;
}


const VpnProtocol& Server::protocol() const {
  return protocol_;
}

void Server::set_protocol(const VpnProtocol& value_arg) {
  protocol_ = value_arg;
}


int64_t Server::routing_profile_id() const {
  return routing_profile_id_;
}

void Server::set_routing_profile_id(int64_t value_arg) {
  routing_profile_id_ = value_arg;
}


const EncodableList& Server::dns_servers() const {
  return dns_servers_;
}

void Server::set_dns_servers(const EncodableList& value_arg) {
  dns_servers_ = value_arg;
}


EncodableList Server::ToEncodableList() const {
  EncodableList list;
  list.reserve(9);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(ip_address_));
  list.push_back(EncodableValue(domain_));
  list.push_back(EncodableValue(login_));
  list.push_back(EncodableValue(password_));
  list.push_back(CustomEncodableValue(protocol_));
  list.push_back(EncodableValue(routing_profile_id_));
  list.push_back(EncodableValue(dns_servers_));
  return list;
}

Server Server::FromEncodableList(const EncodableList& list) {
  Server decoded(
    list[0].LongValue(),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]),
    std::get<std::string>(list[5]),
    std::any_cast<const VpnProtocol&>(std::get<CustomEncodableValue>(list[6])),
    list[7].LongValue(),
    std::get<EncodableList>(list[8]));
  return decoded;
}

// RoutingProfile

RoutingProfile::RoutingProfile(
  int64_t id,
  const std::string& name,
  const RoutingMode& default_mode,
  const EncodableList& bypass_rules,
  const EncodableList& vpn_rules)
 : id_(id),
    name_(name),
    default_mode_(default_mode),
    bypass_rules_(bypass_rules),
    vpn_rules_(vpn_rules) {}

int64_t RoutingProfile::id() const {
  return id_;
}

void RoutingProfile::set_id(int64_t value_arg) {
  id_ = value_arg;
}


const std::string& RoutingProfile::name() const {
  return name_;
}

void RoutingProfile::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const RoutingMode& RoutingProfile::default_mode() const {
  return default_mode_;
}

void RoutingProfile::set_default_mode(const RoutingMode& value_arg) {
  default_mode_ = value_arg;
}


const EncodableList& RoutingProfile::bypass_rules() const {
  return bypass_rules_;
}

void RoutingProfile::set_bypass_rules(const EncodableList& value_arg) {
  bypass_rules_ = value_arg;
}


const EncodableList& RoutingProfile::vpn_rules() const {
  return vpn_rules_;
}

void RoutingProfile::set_vpn_rules(const EncodableList& value_arg) {
  vpn_rules_ = value_arg;
}


EncodableList RoutingProfile::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(name_));
  list.push_back(CustomEncodableValue(default_mode_));
  list.push_back(EncodableValue(bypass_rules_));
  list.push_back(EncodableValue(vpn_rules_));
  return list;
}

RoutingProfile RoutingProfile::FromEncodableList(const EncodableList& list) {
  RoutingProfile decoded(
    list[0].LongValue(),
    std::get<std::string>(list[1]),
    std::any_cast<const RoutingMode&>(std::get<CustomEncodableValue>(list[2])),
    std::get<EncodableList>(list[3]),
    std::get<EncodableList>(list[4]));
  return decoded;
}

// VpnRequest

VpnRequest::VpnRequest(
  const std::string& time,
  const std::string& protocol,
  const RoutingMode& decision,
  const std::string& source_ip_address,
  const std::string& destination_ip_address)
 : time_(time),
    protocol_(protocol),
    decision_(decision),
    source_ip_address_(source_ip_address),
    destination_ip_address_(destination_ip_address) {}

VpnRequest::VpnRequest(
  const std::string& time,
  const std::string& protocol,
  const RoutingMode& decision,
  const std::string& source_ip_address,
  const std::string& destination_ip_address,
  const std::string* source_port,
  const std::string* destination_port,
  const std::string* domain)
 : time_(time),
    protocol_(protocol),
    decision_(decision),
    source_ip_address_(source_ip_address),
    destination_ip_address_(destination_ip_address),
    source_port_(source_port ? std::optional<std::string>(*source_port) : std::nullopt),
    destination_port_(destination_port ? std::optional<std::string>(*destination_port) : std::nullopt),
    domain_(domain ? std::optional<std::string>(*domain) : std::nullopt) {}

const std::string& VpnRequest::time() const {
  return time_;
}

void VpnRequest::set_time(std::string_view value_arg) {
  time_ = value_arg;
}


const std::string& VpnRequest::protocol() const {
  return protocol_;
}

void VpnRequest::set_protocol(std::string_view value_arg) {
  protocol_ = value_arg;
}


const RoutingMode& VpnRequest::decision() const {
  return decision_;
}

void VpnRequest::set_decision(const RoutingMode& value_arg) {
  decision_ = value_arg;
}


const std::string& VpnRequest::source_ip_address() const {
  return source_ip_address_;
}

void VpnRequest::set_source_ip_address(std::string_view value_arg) {
  source_ip_address_ = value_arg;
}


const std::string& VpnRequest::destination_ip_address() const {
  return destination_ip_address_;
}

void VpnRequest::set_destination_ip_address(std::string_view value_arg) {
  destination_ip_address_ = value_arg;
}


const std::string* VpnRequest::source_port() const {
  return source_port_ ? &(*source_port_) : nullptr;
}

void VpnRequest::set_source_port(const std::string_view* value_arg) {
  source_port_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void VpnRequest::set_source_port(std::string_view value_arg) {
  source_port_ = value_arg;
}


const std::string* VpnRequest::destination_port() const {
  return destination_port_ ? &(*destination_port_) : nullptr;
}

void VpnRequest::set_destination_port(const std::string_view* value_arg) {
  destination_port_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void VpnRequest::set_destination_port(std::string_view value_arg) {
  destination_port_ = value_arg;
}


const std::string* VpnRequest::domain() const {
  return domain_ ? &(*domain_) : nullptr;
}

void VpnRequest::set_domain(const std::string_view* value_arg) {
  domain_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void VpnRequest::set_domain(std::string_view value_arg) {
  domain_ = value_arg;
}


EncodableList VpnRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(EncodableValue(time_));
  list.push_back(EncodableValue(protocol_));
  list.push_back(CustomEncodableValue(decision_));
  list.push_back(EncodableValue(source_ip_address_));
  list.push_back(EncodableValue(destination_ip_address_));
  list.push_back(source_port_ ? EncodableValue(*source_port_) : EncodableValue());
  list.push_back(destination_port_ ? EncodableValue(*destination_port_) : EncodableValue());
  list.push_back(domain_ ? EncodableValue(*domain_) : EncodableValue());
  return list;
}

VpnRequest VpnRequest::FromEncodableList(const EncodableList& list) {
  VpnRequest decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::any_cast<const RoutingMode&>(std::get<CustomEncodableValue>(list[2])),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]));
  auto& encodable_source_port = list[5];
  if (!encodable_source_port.IsNull()) {
    decoded.set_source_port(std::get<std::string>(encodable_source_port));
  }
  auto& encodable_destination_port = list[6];
  if (!encodable_destination_port.IsNull()) {
    decoded.set_destination_port(std::get<std::string>(encodable_destination_port));
  }
  auto& encodable_domain = list[7];
  if (!encodable_domain.IsNull()) {
    decoded.set_domain(std::get<std::string>(encodable_domain));
  }
  return decoded;
}

// AddServerRequest

AddServerRequest::AddServerRequest(
  const std::string& name,
  const std::string& ip_address,
  const std::string& domain,
  const std::string& login,
  const std::string& password,
  const VpnProtocol& protocol,
  int64_t routing_profile_id,
  const EncodableList& dns_servers)
 : name_(name),
    ip_address_(ip_address),
    domain_(domain),
    login_(login),
    password_(password),
    protocol_(protocol),
    routing_profile_id_(routing_profile_id),
    dns_servers_(dns_servers) {}

const std::string& AddServerRequest::name() const {
  return name_;
}

void AddServerRequest::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& AddServerRequest::ip_address() const {
  return ip_address_;
}

void AddServerRequest::set_ip_address(std::string_view value_arg) {
  ip_address_ = value_arg;
}


const std::string& AddServerRequest::domain() const {
  return domain_;
}

void AddServerRequest::set_domain(std::string_view value_arg) {
  domain_ = value_arg;
}


const std::string& AddServerRequest::login() const {
  return login_;
}

void AddServerRequest::set_login(std::string_view value_arg) {
  login_ = value_arg;
}


const std::string& AddServerRequest::password() const {
  return password_;
}

void AddServerRequest::set_password(std::string_view value_arg) {
  password_ = value_arg;
}


const VpnProtocol& AddServerRequest::protocol() const {
  return protocol_;
}

void AddServerRequest::set_protocol(const VpnProtocol& value_arg) {
  protocol_ = value_arg;
}


int64_t AddServerRequest::routing_profile_id() const {
  return routing_profile_id_;
}

void AddServerRequest::set_routing_profile_id(int64_t value_arg) {
  routing_profile_id_ = value_arg;
}


const EncodableList& AddServerRequest::dns_servers() const {
  return dns_servers_;
}

void AddServerRequest::set_dns_servers(const EncodableList& value_arg) {
  dns_servers_ = value_arg;
}


EncodableList AddServerRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(ip_address_));
  list.push_back(EncodableValue(domain_));
  list.push_back(EncodableValue(login_));
  list.push_back(EncodableValue(password_));
  list.push_back(CustomEncodableValue(protocol_));
  list.push_back(EncodableValue(routing_profile_id_));
  list.push_back(EncodableValue(dns_servers_));
  return list;
}

AddServerRequest AddServerRequest::FromEncodableList(const EncodableList& list) {
  AddServerRequest decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]),
    std::any_cast<const VpnProtocol&>(std::get<CustomEncodableValue>(list[5])),
    list[6].LongValue(),
    std::get<EncodableList>(list[7]));
  return decoded;
}

// UpdateServerRequest

UpdateServerRequest::UpdateServerRequest(
  int64_t id,
  const std::string& name,
  const std::string& ip_address,
  const std::string& domain,
  const std::string& login,
  const std::string& password,
  const VpnProtocol& protocol,
  int64_t routing_profile_id,
  const EncodableList& dns_servers)
 : id_(id),
    name_(name),
    ip_address_(ip_address),
    domain_(domain),
    login_(login),
    password_(password),
    protocol_(protocol),
    routing_profile_id_(routing_profile_id),
    dns_servers_(dns_servers) {}

int64_t UpdateServerRequest::id() const {
  return id_;
}

void UpdateServerRequest::set_id(int64_t value_arg) {
  id_ = value_arg;
}


const std::string& UpdateServerRequest::name() const {
  return name_;
}

void UpdateServerRequest::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& UpdateServerRequest::ip_address() const {
  return ip_address_;
}

void UpdateServerRequest::set_ip_address(std::string_view value_arg) {
  ip_address_ = value_arg;
}


const std::string& UpdateServerRequest::domain() const {
  return domain_;
}

void UpdateServerRequest::set_domain(std::string_view value_arg) {
  domain_ = value_arg;
}


const std::string& UpdateServerRequest::login() const {
  return login_;
}

void UpdateServerRequest::set_login(std::string_view value_arg) {
  login_ = value_arg;
}


const std::string& UpdateServerRequest::password() const {
  return password_;
}

void UpdateServerRequest::set_password(std::string_view value_arg) {
  password_ = value_arg;
}


const VpnProtocol& UpdateServerRequest::protocol() const {
  return protocol_;
}

void UpdateServerRequest::set_protocol(const VpnProtocol& value_arg) {
  protocol_ = value_arg;
}


int64_t UpdateServerRequest::routing_profile_id() const {
  return routing_profile_id_;
}

void UpdateServerRequest::set_routing_profile_id(int64_t value_arg) {
  routing_profile_id_ = value_arg;
}


const EncodableList& UpdateServerRequest::dns_servers() const {
  return dns_servers_;
}

void UpdateServerRequest::set_dns_servers(const EncodableList& value_arg) {
  dns_servers_ = value_arg;
}


EncodableList UpdateServerRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(9);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(ip_address_));
  list.push_back(EncodableValue(domain_));
  list.push_back(EncodableValue(login_));
  list.push_back(EncodableValue(password_));
  list.push_back(CustomEncodableValue(protocol_));
  list.push_back(EncodableValue(routing_profile_id_));
  list.push_back(EncodableValue(dns_servers_));
  return list;
}

UpdateServerRequest UpdateServerRequest::FromEncodableList(const EncodableList& list) {
  UpdateServerRequest decoded(
    list[0].LongValue(),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]),
    std::get<std::string>(list[5]),
    std::any_cast<const VpnProtocol&>(std::get<CustomEncodableValue>(list[6])),
    list[7].LongValue(),
    std::get<EncodableList>(list[8]));
  return decoded;
}

// AddRoutingProfileRequest

AddRoutingProfileRequest::AddRoutingProfileRequest(
  const std::string& name,
  const RoutingMode& default_mode,
  const EncodableList& bypass_rules,
  const EncodableList& vpn_rules)
 : name_(name),
    default_mode_(default_mode),
    bypass_rules_(bypass_rules),
    vpn_rules_(vpn_rules) {}

const std::string& AddRoutingProfileRequest::name() const {
  return name_;
}

void AddRoutingProfileRequest::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const RoutingMode& AddRoutingProfileRequest::default_mode() const {
  return default_mode_;
}

void AddRoutingProfileRequest::set_default_mode(const RoutingMode& value_arg) {
  default_mode_ = value_arg;
}


const EncodableList& AddRoutingProfileRequest::bypass_rules() const {
  return bypass_rules_;
}

void AddRoutingProfileRequest::set_bypass_rules(const EncodableList& value_arg) {
  bypass_rules_ = value_arg;
}


const EncodableList& AddRoutingProfileRequest::vpn_rules() const {
  return vpn_rules_;
}

void AddRoutingProfileRequest::set_vpn_rules(const EncodableList& value_arg) {
  vpn_rules_ = value_arg;
}


EncodableList AddRoutingProfileRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(name_));
  list.push_back(CustomEncodableValue(default_mode_));
  list.push_back(EncodableValue(bypass_rules_));
  list.push_back(EncodableValue(vpn_rules_));
  return list;
}

AddRoutingProfileRequest AddRoutingProfileRequest::FromEncodableList(const EncodableList& list) {
  AddRoutingProfileRequest decoded(
    std::get<std::string>(list[0]),
    std::any_cast<const RoutingMode&>(std::get<CustomEncodableValue>(list[1])),
    std::get<EncodableList>(list[2]),
    std::get<EncodableList>(list[3]));
  return decoded;
}

// UpdateRoutingProfileRequest

UpdateRoutingProfileRequest::UpdateRoutingProfileRequest(
  const std::string& id,
  const std::string& name,
  const RoutingMode& default_mode,
  const EncodableList& bypass_rules,
  const EncodableList& vpn_rules)
 : id_(id),
    name_(name),
    default_mode_(default_mode),
    bypass_rules_(bypass_rules),
    vpn_rules_(vpn_rules) {}

const std::string& UpdateRoutingProfileRequest::id() const {
  return id_;
}

void UpdateRoutingProfileRequest::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string& UpdateRoutingProfileRequest::name() const {
  return name_;
}

void UpdateRoutingProfileRequest::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const RoutingMode& UpdateRoutingProfileRequest::default_mode() const {
  return default_mode_;
}

void UpdateRoutingProfileRequest::set_default_mode(const RoutingMode& value_arg) {
  default_mode_ = value_arg;
}


const EncodableList& UpdateRoutingProfileRequest::bypass_rules() const {
  return bypass_rules_;
}

void UpdateRoutingProfileRequest::set_bypass_rules(const EncodableList& value_arg) {
  bypass_rules_ = value_arg;
}


const EncodableList& UpdateRoutingProfileRequest::vpn_rules() const {
  return vpn_rules_;
}

void UpdateRoutingProfileRequest::set_vpn_rules(const EncodableList& value_arg) {
  vpn_rules_ = value_arg;
}


EncodableList UpdateRoutingProfileRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(name_));
  list.push_back(CustomEncodableValue(default_mode_));
  list.push_back(EncodableValue(bypass_rules_));
  list.push_back(EncodableValue(vpn_rules_));
  return list;
}

UpdateRoutingProfileRequest UpdateRoutingProfileRequest::FromEncodableList(const EncodableList& list) {
  UpdateRoutingProfileRequest decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::any_cast<const RoutingMode&>(std::get<CustomEncodableValue>(list[2])),
    std::get<EncodableList>(list[3]),
    std::get<EncodableList>(list[4]));
  return decoded;
}

// PlatformErrorResponse

PlatformErrorResponse::PlatformErrorResponse() {}

PlatformErrorResponse::PlatformErrorResponse(
  const PlatformErrorCode* code,
  const EncodableList* field_errors)
 : code_(code ? std::optional<PlatformErrorCode>(*code) : std::nullopt),
    field_errors_(field_errors ? std::optional<EncodableList>(*field_errors) : std::nullopt) {}

const PlatformErrorCode* PlatformErrorResponse::code() const {
  return code_ ? &(*code_) : nullptr;
}

void PlatformErrorResponse::set_code(const PlatformErrorCode* value_arg) {
  code_ = value_arg ? std::optional<PlatformErrorCode>(*value_arg) : std::nullopt;
}

void PlatformErrorResponse::set_code(const PlatformErrorCode& value_arg) {
  code_ = value_arg;
}


const EncodableList* PlatformErrorResponse::field_errors() const {
  return field_errors_ ? &(*field_errors_) : nullptr;
}

void PlatformErrorResponse::set_field_errors(const EncodableList* value_arg) {
  field_errors_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PlatformErrorResponse::set_field_errors(const EncodableList& value_arg) {
  field_errors_ = value_arg;
}


EncodableList PlatformErrorResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(code_ ? CustomEncodableValue(*code_) : EncodableValue());
  list.push_back(field_errors_ ? EncodableValue(*field_errors_) : EncodableValue());
  return list;
}

PlatformErrorResponse PlatformErrorResponse::FromEncodableList(const EncodableList& list) {
  PlatformErrorResponse decoded;
  auto& encodable_code = list[0];
  if (!encodable_code.IsNull()) {
    decoded.set_code(std::any_cast<const PlatformErrorCode&>(std::get<CustomEncodableValue>(encodable_code)));
  }
  auto& encodable_field_errors = list[1];
  if (!encodable_field_errors.IsNull()) {
    decoded.set_field_errors(std::get<EncodableList>(encodable_field_errors));
  }
  return decoded;
}

// PlatformFieldError

PlatformFieldError::PlatformFieldError(
  const PlatformFieldErrorCode& code,
  const PlatformFieldName& field_name)
 : code_(code),
    field_name_(field_name) {}

const PlatformFieldErrorCode& PlatformFieldError::code() const {
  return code_;
}

void PlatformFieldError::set_code(const PlatformFieldErrorCode& value_arg) {
  code_ = value_arg;
}


const PlatformFieldName& PlatformFieldError::field_name() const {
  return field_name_;
}

void PlatformFieldError::set_field_name(const PlatformFieldName& value_arg) {
  field_name_ = value_arg;
}


EncodableList PlatformFieldError::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(CustomEncodableValue(code_));
  list.push_back(CustomEncodableValue(field_name_));
  return list;
}

PlatformFieldError PlatformFieldError::FromEncodableList(const EncodableList& list) {
  PlatformFieldError decoded(
    std::any_cast<const PlatformFieldErrorCode&>(std::get<CustomEncodableValue>(list[0])),
    std::any_cast<const PlatformFieldName&>(std::get<CustomEncodableValue>(list[1])));
  return decoded;
}


PigeonCodecSerializer::PigeonCodecSerializer() {}

EncodableValue PigeonCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129:
      return CustomEncodableValue(Server::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 130:
      return CustomEncodableValue(RoutingProfile::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 131:
      return CustomEncodableValue(VpnRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 132:
      return CustomEncodableValue(AddServerRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 133:
      return CustomEncodableValue(UpdateServerRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 134:
      return CustomEncodableValue(AddRoutingProfileRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 135:
      return CustomEncodableValue(UpdateRoutingProfileRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 136:
      return CustomEncodableValue(PlatformErrorResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 137:
      return CustomEncodableValue(PlatformFieldError::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 138:
      {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<VpnProtocol>(enum_arg_value));
      }
    case 139:
      {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<RoutingMode>(enum_arg_value));
      }
    case 140:
      {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<VpnManagerState>(enum_arg_value));
      }
    case 141:
      {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformErrorCode>(enum_arg_value));
      }
    case 142:
      {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformFieldErrorCode>(enum_arg_value));
      }
    case 143:
      {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformFieldName>(enum_arg_value));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(Server)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<Server>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RoutingProfile)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<RoutingProfile>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(VpnRequest)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<VpnRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AddServerRequest)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<AddServerRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(UpdateServerRequest)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<UpdateServerRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AddRoutingProfileRequest)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<AddRoutingProfileRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(UpdateRoutingProfileRequest)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<UpdateRoutingProfileRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformErrorResponse)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<PlatformErrorResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformFieldError)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<PlatformFieldError>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(VpnProtocol)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<VpnProtocol>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(RoutingMode)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<RoutingMode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(VpnManagerState)) {
      stream->WriteByte(140);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<VpnManagerState>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformErrorCode)) {
      stream->WriteByte(141);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformErrorCode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformFieldErrorCode)) {
      stream->WriteByte(142);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformFieldErrorCode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformFieldName)) {
      stream->WriteByte(143);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformFieldName>(*custom_value))), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by PlatformApi.
const flutter::StandardMessageCodec& PlatformApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonCodecSerializer::GetInstance());
}

// Sets up an instance of `PlatformApi` to handle messages through the `binary_messenger`.
void PlatformApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  PlatformApi* api) {
  PlatformApi::SetUp(binary_messenger, api, "");
}

void PlatformApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  PlatformApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getAllServers" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<EncodableList> output = api->GetAllServers();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getServerById" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          ErrorOr<Server> output = api->GetServerById(id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.addServer" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const AddServerRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          ErrorOr<Server> output = api->AddServer(request_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.updateServer" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const UpdateServerRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          ErrorOr<Server> output = api->UpdateServer(request_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.removeServer" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          std::optional<FlutterError> output = api->RemoveServer(id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getSelectedServerId" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::optional<int64_t>> output = api->GetSelectedServerId();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(EncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.setSelectedServerId" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          std::optional<FlutterError> output = api->SetSelectedServerId(id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getAllRoutingProfiles" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<EncodableList> output = api->GetAllRoutingProfiles();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getRoutingProfileById" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          ErrorOr<RoutingProfile> output = api->GetRoutingProfileById(id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.addRoutingProfile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const AddRoutingProfileRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          ErrorOr<RoutingProfile> output = api->AddRoutingProfile(request_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.updateRoutingProfile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const UpdateRoutingProfileRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          ErrorOr<RoutingProfile> output = api->UpdateRoutingProfile(request_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.setRoutingProfileName" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_name_arg = args.at(0);
          if (encodable_name_arg.IsNull()) {
            reply(WrapError("name_arg unexpectedly null."));
            return;
          }
          const auto& name_arg = std::get<std::string>(encodable_name_arg);
          std::optional<FlutterError> output = api->SetRoutingProfileName(name_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.removeRoutingProfile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          std::optional<FlutterError> output = api->RemoveRoutingProfile(id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getAllRequests" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<EncodableList> output = api->GetAllRequests();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.start" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Start();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.stop" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Stop();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.getCurrentState" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<VpnManagerState> output = api->GetCurrentState();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.PlatformApi.errorStub" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_error_arg = args.at(0);
          if (encodable_error_arg.IsNull()) {
            reply(WrapError("error_arg unexpectedly null."));
            return;
          }
          const auto& error_arg = std::any_cast<const PlatformErrorResponse&>(std::get<CustomEncodableValue>(encodable_error_arg));
          std::optional<FlutterError> output = api->ErrorStub(error_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue PlatformApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue PlatformApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace vpn_plugin
