// Autogenerated from Pigeon (v21.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PLATFORM_API_G_H_
#define PIGEON_PLATFORM_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace vpn_plugin {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class PlatformApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class VpnProtocol {
  kQuiq = 0,
  kHttp2 = 1
};

enum class RoutingMode {
  kBypass = 0,
  kVpn = 1
};

enum class VpnManagerState {
  kDisconnected = 0,
  kConnecting = 1,
  kConnected = 2
};

enum class PlatformErrorCode {
  kUnknown = 0
};

enum class PlatformFieldErrorCode {
  kFieldWrongValue = 0,
  kAlreadyExists = 1
};

enum class PlatformFieldName {
  kIpAddress = 0,
  kDomain = 1,
  kServerName = 2,
  kDnsServers = 3
};

// Generated class from Pigeon that represents data sent in messages.
class Server {
 public:
  // Constructs an object setting all fields.
  explicit Server(
    int64_t id,
    const std::string& name,
    const std::string& ip_address,
    const std::string& domain,
    const std::string& login,
    const std::string& password,
    const VpnProtocol& protocol,
    int64_t routing_profile_id,
    const flutter::EncodableList& dns_servers);

  int64_t id() const;
  void set_id(int64_t value_arg);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::string& ip_address() const;
  void set_ip_address(std::string_view value_arg);

  const std::string& domain() const;
  void set_domain(std::string_view value_arg);

  const std::string& login() const;
  void set_login(std::string_view value_arg);

  const std::string& password() const;
  void set_password(std::string_view value_arg);

  const VpnProtocol& protocol() const;
  void set_protocol(const VpnProtocol& value_arg);

  int64_t routing_profile_id() const;
  void set_routing_profile_id(int64_t value_arg);

  const flutter::EncodableList& dns_servers() const;
  void set_dns_servers(const flutter::EncodableList& value_arg);


 private:
  static Server FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  int64_t id_;
  std::string name_;
  std::string ip_address_;
  std::string domain_;
  std::string login_;
  std::string password_;
  VpnProtocol protocol_;
  int64_t routing_profile_id_;
  flutter::EncodableList dns_servers_;

};


// Generated class from Pigeon that represents data sent in messages.
class RoutingProfile {
 public:
  // Constructs an object setting all fields.
  explicit RoutingProfile(
    int64_t id,
    const std::string& name,
    const RoutingMode& default_mode,
    const flutter::EncodableList& bypass_rules,
    const flutter::EncodableList& vpn_rules);

  int64_t id() const;
  void set_id(int64_t value_arg);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const RoutingMode& default_mode() const;
  void set_default_mode(const RoutingMode& value_arg);

  const flutter::EncodableList& bypass_rules() const;
  void set_bypass_rules(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& vpn_rules() const;
  void set_vpn_rules(const flutter::EncodableList& value_arg);


 private:
  static RoutingProfile FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  int64_t id_;
  std::string name_;
  RoutingMode default_mode_;
  flutter::EncodableList bypass_rules_;
  flutter::EncodableList vpn_rules_;

};


// Generated class from Pigeon that represents data sent in messages.
class VpnRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VpnRequest(
    const std::string& time,
    const std::string& protocol,
    const RoutingMode& decision,
    const std::string& source_ip_address,
    const std::string& destination_ip_address);

  // Constructs an object setting all fields.
  explicit VpnRequest(
    const std::string& time,
    const std::string& protocol,
    const RoutingMode& decision,
    const std::string& source_ip_address,
    const std::string& destination_ip_address,
    const std::string* source_port,
    const std::string* destination_port,
    const std::string* domain);

  const std::string& time() const;
  void set_time(std::string_view value_arg);

  const std::string& protocol() const;
  void set_protocol(std::string_view value_arg);

  const RoutingMode& decision() const;
  void set_decision(const RoutingMode& value_arg);

  const std::string& source_ip_address() const;
  void set_source_ip_address(std::string_view value_arg);

  const std::string& destination_ip_address() const;
  void set_destination_ip_address(std::string_view value_arg);

  const std::string* source_port() const;
  void set_source_port(const std::string_view* value_arg);
  void set_source_port(std::string_view value_arg);

  const std::string* destination_port() const;
  void set_destination_port(const std::string_view* value_arg);
  void set_destination_port(std::string_view value_arg);

  const std::string* domain() const;
  void set_domain(const std::string_view* value_arg);
  void set_domain(std::string_view value_arg);


 private:
  static VpnRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  std::string time_;
  std::string protocol_;
  RoutingMode decision_;
  std::string source_ip_address_;
  std::string destination_ip_address_;
  std::optional<std::string> source_port_;
  std::optional<std::string> destination_port_;
  std::optional<std::string> domain_;

};


// Generated class from Pigeon that represents data sent in messages.
class AddServerRequest {
 public:
  // Constructs an object setting all fields.
  explicit AddServerRequest(
    const std::string& name,
    const std::string& ip_address,
    const std::string& domain,
    const std::string& login,
    const std::string& password,
    const VpnProtocol& protocol,
    int64_t routing_profile_id,
    const flutter::EncodableList& dns_servers);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::string& ip_address() const;
  void set_ip_address(std::string_view value_arg);

  const std::string& domain() const;
  void set_domain(std::string_view value_arg);

  const std::string& login() const;
  void set_login(std::string_view value_arg);

  const std::string& password() const;
  void set_password(std::string_view value_arg);

  const VpnProtocol& protocol() const;
  void set_protocol(const VpnProtocol& value_arg);

  int64_t routing_profile_id() const;
  void set_routing_profile_id(int64_t value_arg);

  const flutter::EncodableList& dns_servers() const;
  void set_dns_servers(const flutter::EncodableList& value_arg);


 private:
  static AddServerRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  std::string name_;
  std::string ip_address_;
  std::string domain_;
  std::string login_;
  std::string password_;
  VpnProtocol protocol_;
  int64_t routing_profile_id_;
  flutter::EncodableList dns_servers_;

};


// Generated class from Pigeon that represents data sent in messages.
class UpdateServerRequest {
 public:
  // Constructs an object setting all fields.
  explicit UpdateServerRequest(
    int64_t id,
    const std::string& name,
    const std::string& ip_address,
    const std::string& domain,
    const std::string& login,
    const std::string& password,
    const VpnProtocol& protocol,
    int64_t routing_profile_id,
    const flutter::EncodableList& dns_servers);

  int64_t id() const;
  void set_id(int64_t value_arg);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::string& ip_address() const;
  void set_ip_address(std::string_view value_arg);

  const std::string& domain() const;
  void set_domain(std::string_view value_arg);

  const std::string& login() const;
  void set_login(std::string_view value_arg);

  const std::string& password() const;
  void set_password(std::string_view value_arg);

  const VpnProtocol& protocol() const;
  void set_protocol(const VpnProtocol& value_arg);

  int64_t routing_profile_id() const;
  void set_routing_profile_id(int64_t value_arg);

  const flutter::EncodableList& dns_servers() const;
  void set_dns_servers(const flutter::EncodableList& value_arg);


 private:
  static UpdateServerRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  int64_t id_;
  std::string name_;
  std::string ip_address_;
  std::string domain_;
  std::string login_;
  std::string password_;
  VpnProtocol protocol_;
  int64_t routing_profile_id_;
  flutter::EncodableList dns_servers_;

};


// Generated class from Pigeon that represents data sent in messages.
class AddRoutingProfileRequest {
 public:
  // Constructs an object setting all fields.
  explicit AddRoutingProfileRequest(
    const std::string& name,
    const RoutingMode& default_mode,
    const flutter::EncodableList& bypass_rules,
    const flutter::EncodableList& vpn_rules);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const RoutingMode& default_mode() const;
  void set_default_mode(const RoutingMode& value_arg);

  const flutter::EncodableList& bypass_rules() const;
  void set_bypass_rules(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& vpn_rules() const;
  void set_vpn_rules(const flutter::EncodableList& value_arg);


 private:
  static AddRoutingProfileRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  std::string name_;
  RoutingMode default_mode_;
  flutter::EncodableList bypass_rules_;
  flutter::EncodableList vpn_rules_;

};


// Generated class from Pigeon that represents data sent in messages.
class UpdateRoutingProfileRequest {
 public:
  // Constructs an object setting all fields.
  explicit UpdateRoutingProfileRequest(
    const std::string& id,
    const std::string& name,
    const RoutingMode& default_mode,
    const flutter::EncodableList& bypass_rules,
    const flutter::EncodableList& vpn_rules);

  const std::string& id() const;
  void set_id(std::string_view value_arg);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const RoutingMode& default_mode() const;
  void set_default_mode(const RoutingMode& value_arg);

  const flutter::EncodableList& bypass_rules() const;
  void set_bypass_rules(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& vpn_rules() const;
  void set_vpn_rules(const flutter::EncodableList& value_arg);


 private:
  static UpdateRoutingProfileRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  std::string id_;
  std::string name_;
  RoutingMode default_mode_;
  flutter::EncodableList bypass_rules_;
  flutter::EncodableList vpn_rules_;

};


// Generated class from Pigeon that represents data sent in messages.
class PlatformErrorResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  PlatformErrorResponse();

  // Constructs an object setting all fields.
  explicit PlatformErrorResponse(
    const PlatformErrorCode* code,
    const flutter::EncodableList* field_errors);

  const PlatformErrorCode* code() const;
  void set_code(const PlatformErrorCode* value_arg);
  void set_code(const PlatformErrorCode& value_arg);

  const flutter::EncodableList* field_errors() const;
  void set_field_errors(const flutter::EncodableList* value_arg);
  void set_field_errors(const flutter::EncodableList& value_arg);


 private:
  static PlatformErrorResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  std::optional<PlatformErrorCode> code_;
  std::optional<flutter::EncodableList> field_errors_;

};


// Generated class from Pigeon that represents data sent in messages.
class PlatformFieldError {
 public:
  // Constructs an object setting all fields.
  explicit PlatformFieldError(
    const PlatformFieldErrorCode& code,
    const PlatformFieldName& field_name);

  const PlatformFieldErrorCode& code() const;
  void set_code(const PlatformFieldErrorCode& value_arg);

  const PlatformFieldName& field_name() const;
  void set_field_name(const PlatformFieldName& value_arg);


 private:
  static PlatformFieldError FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PlatformApi;
  friend class PigeonCodecSerializer;
  PlatformFieldErrorCode code_;
  PlatformFieldName field_name_;

};

class PigeonCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonCodecSerializer();
  inline static PigeonCodecSerializer& GetInstance() {
    static PigeonCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class PlatformApi {
 public:
  PlatformApi(const PlatformApi&) = delete;
  PlatformApi& operator=(const PlatformApi&) = delete;
  virtual ~PlatformApi() {}
  virtual ErrorOr<flutter::EncodableList> GetAllServers() = 0;
  virtual ErrorOr<Server> GetServerById(int64_t id) = 0;
  virtual ErrorOr<Server> AddServer(const AddServerRequest& request) = 0;
  virtual ErrorOr<Server> UpdateServer(const UpdateServerRequest& request) = 0;
  virtual std::optional<FlutterError> RemoveServer(int64_t id) = 0;
  virtual ErrorOr<std::optional<int64_t>> GetSelectedServerId() = 0;
  virtual std::optional<FlutterError> SetSelectedServerId(int64_t id) = 0;
  virtual ErrorOr<flutter::EncodableList> GetAllRoutingProfiles() = 0;
  virtual ErrorOr<RoutingProfile> GetRoutingProfileById(int64_t id) = 0;
  virtual ErrorOr<RoutingProfile> AddRoutingProfile(const AddRoutingProfileRequest& request) = 0;
  virtual ErrorOr<RoutingProfile> UpdateRoutingProfile(const UpdateRoutingProfileRequest& request) = 0;
  virtual std::optional<FlutterError> SetRoutingProfileName(const std::string& name) = 0;
  virtual std::optional<FlutterError> RemoveRoutingProfile(int64_t id) = 0;
  virtual ErrorOr<flutter::EncodableList> GetAllRequests() = 0;
  virtual std::optional<FlutterError> Start() = 0;
  virtual std::optional<FlutterError> Stop() = 0;
  virtual ErrorOr<VpnManagerState> GetCurrentState() = 0;
  virtual std::optional<FlutterError> ErrorStub(const PlatformErrorResponse& error) = 0;

  // The codec used by PlatformApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `PlatformApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PlatformApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PlatformApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  PlatformApi() = default;

};
}  // namespace vpn_plugin
#endif  // PIGEON_PLATFORM_API_G_H_
