---
version: 2

plan:
  project-key: TT
  key: BUILDINGTODEPLOY
  name: TrustTunnel — building to deploy

stages:
  - Preparing:
      manual: false
      final: false
      jobs:
        - Preparing
  - Building and publishing:
      manual: false
      final: false
      jobs:
        - Building iOS
        - Building Android
  - Posting:
      manual: false
      final: false
      jobs:
        - Posting

notifications: []

labels: []

triggers: []

variables:
  bamboo_build_channel: can be prenightly/nightly/beta/rc/release
  bamboo_distribute_external: false
  bamboo_submit_beta_review: false
  bamboo_postToSlack: true

branches:
  create: manually
  delete: never
  link-to-jira: true

other:
  concurrent-build-plugin: '1'

Preparing:
  key: PREPARING
  docker:
    image: adguard/android-base:2.10
  tasks:
    - !include task-clean-all.yaml
    - checkout:
        path: trusttunnel
        force-clean-build: true
    - script: trusttunnel/bamboo-specs/scripts/check_variables.sh
    - checkout:
        repository: git-scripts
        path: git-scripts
        force-clean-build: true
    - checkout:
        repository: bamboo-scripts
        path: bamboo-scripts
        force-clean-build: true
    - script: python3 trusttunnel/bamboo-scripts/bamboo-kit.py addLabelToPlan --project-key TT --plan-key BUILDINGTODEPLOY --build-number "${bamboo.buildNumber}" --label "${bamboo_build_channel}"
    - script: trusttunnel/bamboo-specs/scripts/collect_changelog_retag_collect_variables.sh "${bamboo_working_directory}/git-scripts/git_kit.sh"
    - inject-variables:
        file: trusttunnel/variables.txt
        scope: result
        namespace: data
  final-tasks:
    - script: find . -mindepth 1 \( -path "./trusttunnel/changelog.txt" -o -path "./trusttunnel/qa_changelog.md" -o -path "./trusttunnel/variables.txt" \) -o -delete; exit 0
  artifacts:
    - name: changelog.txt
      location: trusttunnel
      pattern: changelog.txt
      shared: true
      required: true
    - name: qa_changelog.md
      location: trusttunnel
      pattern: qa_changelog.md
      shared: true
      required: true
    - name: variables.txt
      location: trusttunnel
      pattern: variables.txt
      shared: true
      required: true
  requirements: [ adg-privileged-docker ]

Building iOS:
  key: IOSBUILDINGIOS
  tasks:
    - !include task-clean-all.yaml
    - checkout:
        path: trusttunnel
        force-clean-build: true
    - script: trusttunnel/bamboo-specs/scripts/setup_ssh.sh
    - script: trusttunnel/bamboo-specs/scripts/print_all_required_info.sh
    - script: trusttunnel/bamboo-specs/scripts/configure_before_ios_build.sh "${bamboo_build_channel}" "$PWD/trusttunnel"
    - script: trusttunnel/bamboo-specs/scripts/build_ipa.sh "appstore" "true"
    - script: cp "trusttunnel/ios/build/TrustTunnel.ipa" "trusttunnel/TrustTunnel.ipa"
    - script: trusttunnel/bamboo-specs/scripts/build_app_and_zip.sh "${bamboo_build_channel}"
    - script: cp "trusttunnel/ios/build/TrustTunnel.app.zip" "trusttunnel/TrustTunnel.app.zip"
  final-tasks:
    - script: find . -mindepth 1 \( -path "./trusttunnel/TrustTunnel.ipa" -o -path "./trusttunnel/TrustTunnel.app.zip" \) -o -delete; exit 0
  artifacts:
    - name: TrustTunnel.ipa
      location: trusttunnel
      pattern: 'TrustTunnel.ipa'
      shared: true
      required: true
    - name: TrustTunnel.app.zip
      location: trusttunnel
      pattern: 'TrustTunnel.app.zip'
      shared: true
      required: true
  requirements:
    - ephemeral
    - image: registry.int.agrd.dev/macos/tahoe-build-agent-xcode26.1.1:latest

Building Android:
  key: BUILDINGANDROID
  tasks:
    - !include task-clean-all.yaml
    - checkout:
        force-clean-build: true
    - script:
        scripts:
          - bamboo-specs/scripts/configure_before_android_build.sh "${PWD}/android"
          - bamboo-specs/scripts/build_android.sh apk
  final-tasks:
    - script: find . -mindepth 1 \( -path "./build/app/outputs/flutter-apk/app-release.apk" \) -o -delete; exit 0
  artifacts:
    - name: app-release.apk
      location: build/app/outputs/flutter-apk/
      pattern: 'app-release.apk'
      shared: true
      required: true
  requirements:
    - ephemeral
    - image: registry.int.agrd.dev/macos/tahoe-build-agent-xcode26.1.1:latest

Posting:
  key: POSTING
  docker:
    image: adguard/android-base:2.10
  tasks:
    - script: ls -laR
    - checkout:
        path: trusttunnel
        force-clean-build: true
    - checkout:
        repository: slack-scripts
        path: slack-scripts
        force-clean-build: true
    - script: trusttunnel/bamboo-specs/scripts/post_requisite_to_slack.sh "${bamboo_build_channel}" "${bamboo_working_directory}/slack-scripts/slack_kit.py"
  final-tasks:
    - !include task-clean-all.yaml
  requirements: [ adg-privileged-docker ]

